# Cloudflare Pages configuration
name = "oscar-zone"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
